{% set name = "jupyterlab-stickyland" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyterlab_stickyland-{{ version }}.tar.gz
  sha256: 2c30ffd8c1ad1815afd7ee5e1b89add2b59c05974bd9bf621ac90691e5f32ebc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - jupyterlab <=3.6.4
    - jupyter-packaging ~=0.10,<2
    - pip
    - python >=3.6
  run:
    - jupyterlab <=3.6.4
    - python >=3.6

test:
  imports:
    - jupyterlab_stickyland
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/xiaohk/stickyland
  summary: Break free from the linear presentation of Jupyter Notebooks with sticky cells!
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
